# Generated by Django 2.0.7 on 2018-07-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/<django.db.models.fields.CharField>/avatars/'),
        ),
    ]
